spring:
  application:
    name: nearpick-backend
  profiles:
    active: local

server:
  port: 8080

springdoc:
    api-docs:
        path: /v3/api-docs
    swagger-ui:
        path: /swagger-ui.html
        display-request-duration: true
        doc-expansion: none
        operations-sorter: method
        tags-sorter: alpha

logging:
  level:
    root: INFO
    com.nearpick: DEBUG